### ISSUE TITLE
Background for structure

### ISSUE THREAD

**Issue by askholme** [saltstack-formulas/os-hardening-formula#5]
Wondering why you have chosen the templates paths like so

the init.ssl file says salt:://linux/hardening/...
but the state is named os-hardening and has a sub folder called ubuntu which more looks like 
salt://os-hardening/ubuntu

With the current naming i would have to get the formula down, rename it to linux and them rename it's sub-folder ubuntu to hardening in order to get stuff working?

**Comment by askholme** [comment]
Umm. Actually that doesn't really solve the issue.
At least not if you want to comply with the default structure on the saltstack-formulas repo.

As per examples https://github.com/saltstack-formulas/nginx-formula and https://github.com/saltstack-formulas/logrotate-formula the name of the git-repo it-self is not seen as being part of the formula path.
So with the current naming the path should be salt://ubuntu/templates/...

In my PR i address this by changing the name of the ubuntu folder

**Comment by nmadhok** [comment]
@askholme Look at https://github.com/saltstack-formulas/os-hardening-formula/pull/6

**Comment by askholme** [comment]
Ah, fair enough :-).

I'll rebase my stuff on that if #6 is merged then

**Comment by nmadhok** [comment]
@askholme Merging it right away!
